name: cleverpush_flutter
description: CleverPush
version: 1.22.1
homepage: https://github.com/cleverpush/cleverpush-flutter-sdk

flutter:
  plugin:
    platforms:
      android:
        package: com.cleverpush.flutter
        pluginClass: CleverPushPlugin
      ios:
        pluginClass: CleverPushPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'
